/* eslint-disable max-len */
export const dummyArray = [
  {
    name: "MEN'S JACKET",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/mens-better-than-naked-jacket-AVMH_LC9_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/men-39-s-better-than-naked-8482-jacket.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-mens/',
    textNow: 'Shop Now',
    likes: 27,
    views: 1710,
    id: 1,
  },
  {
    name: "WOMEN'S JACKET",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-better-than-naked-jacket-AVKL_NN4_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/women-39-s-better-than-naked-8482-jacket.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-womens/',
    textNow: 'Shop Now',
    likes: 5,
    views: 540,
    id: 2,
  },
  {
    name: "WOMEN'S SINGLE-TRACK SHOE",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-single-track-shoe-ALQF_JM3_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/womens-single-track.html',
    productUrl: 'http://www.thenorthface.com/webapp/wcs/stores/servlet/TNFSearchResult?langId=-1&amp;storeId=207&amp;catalogId=10201&amp;searchTerm=running%20shoes',
    textNow: 'Shop Now',
    likes: 9,
    views: 999,
    id: 3,
  },
  {
    name: 'ENDURO HYDRATION PACK',
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/enduro-boa-hydration-pack-AJQZ_JK3_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/enduro-boa.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-equipment/',
    textNow: 'Shop Now',
    likes: 12,
    views: 2214,
    id: 4,
  },
  {
    name: "MEN'S JACKET",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/mens-better-than-naked-jacket-AVMH_LC9_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/men-39-s-better-than-naked-8482-jacket.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-mens/',
    textNow: 'Shop Now',
    likes: 45,
    views: 4599,
    id: 5,
  },
  {
    name: "WOMEN'S JACKET",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-better-than-naked-jacket-AVKL_NN4_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/women-39-s-better-than-naked-8482-jacket.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-womens/',
    textNow: 'Shop Now',
    likes: 18,
    views: 763,
    id: 6,
  },
  {
    name: "WOMEN'S SINGLE-TRACK SHOE",
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-single-track-shoe-ALQF_JM3_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/womens-single-track.html',
    productUrl: 'http://www.thenorthface.com/webapp/wcs/stores/servlet/TNFSearchResult?langId=-1&amp;storeId=207&amp;catalogId=10201&amp;searchTerm=running%20shoes',
    textNow: 'Shop Now',
    likes: 36,
    views: 2430,
    id: 7,
  },
  {
    name: 'ENDURO HYDRATION PACK',
    image: 'http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/enduro-boa-hydration-pack-AJQZ_JK3_hero.png',
    textAll: 'Shop All',
    url: 'http://www.thenorthface.com/catalog/sc-gear/enduro-boa.html',
    productUrl: 'http://www.thenorthface.com/en_US/shop-equipment/',
    textNow: 'Shop Now',
    likes: 54,
    views: 1206,
    id: 8,
  },
];
